language: python

env:
  - TOX_ENV=py27
  - TOX_ENV=py27-configparser
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
install:
  - git config --global user.email "bumpversion-test-git@travis.ci"
  - git config --global user.name "Testing Git on Travis CI"
  - git --version
  - git config --list
  - echo -e '[ui]\nusername = Testing Mercurial on Travis CI <bumpversion-test-hg@travis.ci>' > ~/.hgrc
  - hg --version
  - travis_retry pip install "virtualenv<14.0.0" pytest tox

script:
  - tox -e $TOX_ENV

